### ISSUE TITLE
AttributeError: 'PointerLSTM' object has no attribute 'get_initial_states'

### ISSUE THREAD

**Issue by unnir** [zygmuntz/pointer-networks-experiments#2]
Trying to start the script getting this error message:

`AttributeError: 'PointerLSTM' object has no attribute 'get_initial_states'
`

**Comment by zygmuntz** [comment]
You might try Keras 2 branch:
https://github.com/zygmuntz/pointer-networks-experiments/tree/keras-2.0

**Comment by unnir** [comment]
thank you!
